project:
  type: website
  output-dir: docs

website:
  title: "Michelle Yiv"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: simplex
      dark: superhero
    css: styles.css
    toc: false #can enable toc on a page by page basis
    page-layout: full



